// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Net6.SFTP.Services.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Net6.SFTP.Services.Migrations
{
    [DbContext(typeof(SftpInfoDb))]
    partial class SftpInfoDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Net6.SFTP.Services.Models.SftpFileInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FileDowloadTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastAccessTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastWriteTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LocalFilePath")
                        .HasColumnType("text");

                    b.Property<string>("RemoteFilePath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SftpFileInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
